"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { type Application, blankApplication, JOB_STATES, type ApplicationRecord } from "@/lib/workspace/model";
import { control, Field, useWorkspaceCopy, workspaceApi } from "./shared";
function editable(r: Application): Application { return { company:r.company, position:r.position, link:r.link, status:r.status, notes:r.notes, follow_up:r.follow_up, letter_id:r.letter_id }; }
export function JobsBoard({ letters, lettersError = false }: { letters: {id:string;label:string}[]; lettersError?:boolean }) {
 const c=useWorkspaceCopy();
 const [items,setItems]=useState<ApplicationRecord[]>([]),[draft,setDraft]=useState<Application|null>(null),[editing,setEditing]=useState(""),[search,setSearch]=useState(""),[filter,setFilter]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState<"error"|"invalid"|"">(""),[confirm,setConfirm]=useState("");
 async function load(){setLoading(true);setError("");try{setItems(await workspaceApi<ApplicationRecord[]>("/api/workspace/jobs"));}catch{setError("error");}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 async function persist(value:Application,id=""){setBusy(true);setError("");try{const row=await workspaceApi<ApplicationRecord>(`/api/workspace/jobs${id?`/${id}`:""}`,id?"PUT":"POST",editable(value));setItems(old=>id?old.map(r=>r.id===id?row:r):[row,...old]);return true;}catch(e){setError(e instanceof Error&&e.message==="invalid"?"invalid":"error");return false;}finally{setBusy(false);}}
 async function remove(id:string){setBusy(true);setError("");try{await workspaceApi(`/api/workspace/jobs/${id}`,"DELETE");setItems(old=>old.filter(r=>r.id!==id));if(editing===id)setDraft(null);setConfirm("");}catch{setError("error");}finally{setBusy(false);}}
 function edit(row?:ApplicationRecord){setEditing(row?.id||"");setDraft(row?editable(row):blankApplication());window.scrollTo({top:0,behavior:"smooth"});}
 const now=new Date(),today=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,"0")}-${String(now.getDate()).padStart(2,"0")}`;
 const visible=items.filter(r=>(!filter||r.status===filter)&&`${r.company} ${r.position}`.toLowerCase().includes(search.toLowerCase()));
 return <main className="mx-auto max-w-5xl px-4 py-8 sm:px-8"><header className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-2xl font-semibold">{c.jobs}</h1><p className="mt-2 text-muted-foreground">{c.jobIntro}</p></div><Button disabled={busy} onClick={()=>edit()}>{c.newJob}</Button></header>
 {(error||lettersError)&&<p role="alert" className="mt-4">{c[error||"error"]} {!draft&&<Button variant="outline" onClick={()=>void load()}>{c.retry}</Button>}</p>}
 {draft&&<form className="mt-6 rounded-xl border border-border bg-surface p-4 sm:p-6" onSubmit={e=>{e.preventDefault();void persist(draft,editing).then(ok=>{if(ok){setDraft(null);setEditing("");}});}}><fieldset disabled={busy} className="grid gap-4 sm:grid-cols-2">{(["company","position","link","follow_up"] as const).map(key=><Field key={key} label={c[key]}><input className={control} required={key==="company"||key==="position"} type={key==="link"?"url":key==="follow_up"?"date":"text"} maxLength={key==="link"?2000:300} value={draft[key]} onChange={e=>setDraft({...draft,[key]:e.target.value})}/></Field>)}<Field label={c.status}><select className={control} value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value as Application["status"]})}>{JOB_STATES.map(s=><option key={s} value={s}>{c.states[s]}</option>)}</select></Field><Field label={c.letter_id}><select className={control} value={draft.letter_id} onChange={e=>setDraft({...draft,letter_id:e.target.value})}><option value="">{c.noLetter}</option>{letters.map(l=><option key={l.id} value={l.id}>{l.label}</option>)}</select></Field><div className="sm:col-span-2"><Field label={c.notes}><textarea className={control} rows={4} maxLength={10000} value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})}/></Field></div><div className="flex gap-2"><Button type="submit">{busy?c.saving:c.save}</Button><Button type="button" variant="outline" onClick={()=>setDraft(null)}>{c.cancel}</Button></div></fieldset></form>}
 <div className="my-6 grid gap-3 sm:grid-cols-2"><Field label={c.search}><input className={control} value={search} onChange={e=>setSearch(e.target.value)}/></Field><Field label={c.status}><select className={control} value={filter} onChange={e=>setFilter(e.target.value)}><option value="">{c.all} ({items.length})</option>{JOB_STATES.map(s=><option key={s} value={s}>{c.states[s]} ({items.filter(r=>r.status===s).length})</option>)}</select></Field></div>
 <div className="space-y-3">{visible.map(r=><article key={r.id} className="min-w-0 rounded-xl border border-border bg-surface p-4 sm:p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div className="min-w-0 flex-1"><h2 className="break-words text-lg font-semibold">{r.position}</h2><p className="break-words text-sm text-muted-foreground">{r.company}</p>{r.follow_up&&<p className="mt-2 text-sm">{c.follow_up}: {r.follow_up} {r.follow_up<=today&&!["offer","rejected"].includes(r.status)&&<span className="font-semibold">· {c.due}</span>}</p>}</div><label className="max-w-full text-sm"><span className="sr-only">{c.status}: {r.company}</span><select disabled={busy} className={control} value={r.status} onChange={e=>void persist({...editable(r),status:e.target.value as Application["status"]},r.id)}>{JOB_STATES.map(s=><option key={s} value={s}>{c.states[s]}</option>)}</select></label></div>{r.notes&&<p className="mt-3 whitespace-pre-wrap break-words text-sm text-muted-foreground">{r.notes}</p>}<div className="mt-4 flex flex-wrap items-center gap-2"><Button disabled={busy} variant="outline" onClick={()=>edit(r)}>{c.edit}</Button>{r.link&&<a href={r.link} target="_blank" rel="noopener noreferrer" className="px-2 text-sm underline">{c.link}</a>}{r.letter_id&&letters.some(l=>l.id===r.letter_id)&&<Link className="px-2 text-sm underline" href={`/cover-letters/${r.letter_id}`}>{c.openLetter}</Link>}<Button disabled={busy} variant="ghost" onClick={()=>confirm===r.id?void remove(r.id):setConfirm(r.id)}>{confirm===r.id?c.confirm:c.remove}</Button>{confirm===r.id&&<Button variant="ghost" onClick={()=>setConfirm("")}>{c.cancel}</Button>}</div></article>)}</div>{loading?<p role="status">{c.loading}</p>:!visible.length&&!error&&<p className="rounded-lg border border-dashed border-border p-8 text-muted-foreground">{c.empty}</p>}</main>;
}
